ALTER TABLE "PlatformSettings"
  ADD COLUMN IF NOT EXISTS "riderBasePay"  INTEGER NOT NULL DEFAULT 2500,
  ADD COLUMN IF NOT EXISTS "riderPerKmPay" INTEGER NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS "riderMinPayout" INTEGER NOT NULL DEFAULT 2000;
